### PR TITLE
Add StatusForbiddenError and matcher for apimachinery correspondent

### PR DESCRIPTION
**Pull request by tuommaki**
Add StatusForbiddenError and matcher for corresponding apimachinery
StatusError with Forbidden Reason.

Towards https://github.com/giantswarm/giantswarm/issues/3458 to improve also error handling.

### CODE REVIEW

**Comment by tuommaki** [comment]
Oh gosh, dependencies...

**Comment by xh3b4sd** [comment]
I wonder why most of the code is not pruned. Some `dep` magic we miss? Also, why adding this here? Do we need the forbidden checks in different repos? Maybe just add it to `operatorkit` where we actually need it.

**Comment by tuommaki** [comment]
> I wonder why most of the code is not pruned. Some dep magic we miss? 

Maybe `dep` isn't able to infer it correctly when `main()` is missing?

> Also, why adding this here? Do we need the forbidden checks in different repos? Maybe just add it to operatorkit where we actually need it.

Ok. I misunderstood your comment in Slack. I was initially meaning to place this in OperatorKit but somehow interpreted that you saw this repo as better place. I'll drop this PR and move there.

**Comment by xh3b4sd** [comment]
I see. I just wanted to refer to the lib because of the tests, which are really useful.

**Pull request closed without merging**
