### PR TITLE
Migrate from dep to Go modules

### PR DESCRIPTION
**Pull request by rossf7**
Towards https://github.com/giantswarm/giantswarm/issues/5680

Should we also switch to architect-orb in these PRs?

### CODE REVIEW

**Comment by omegas27** [comment]
As it depends on github.com/giantswarm/microerror, should we not release (v1.0.0) microerror before merging this one?

**Comment by rossf7** [comment]
@omegas27 > should we not release (v1.0.0) microerror before merging this one?

With dep we keep the PRs open until we are ready to merge all components. Not sure yet how the process changes with Go modules.

**Comment by omegas27** [comment]
Alright, we can start the work that way then. This can be a topic for the working group then

**Comment by kopiczko** [comment]
Replacing this.

**Pull request closed without merging**
